<?php
header("Content-Type: text/cache-manifest; charset=UTF-8");
?>
CACHE MANIFEST

../offline.html
style.mobile.css
XHConn.js
../offline.js
./data_not_avail.jpg 
../../lib/OpenLayers.js
../../lib/OpenLayers/BaseTypes/Class.js
../../lib/OpenLayers/BaseTypes.js
../../lib/OpenLayers/BaseTypes/Bounds.js
../../lib/OpenLayers/BaseTypes/Date.js
../../lib/OpenLayers/Util.js
../../lib/OpenLayers/BaseTypes/Element.js
../../lib/OpenLayers/BaseTypes/LonLat.js
../../lib/OpenLayers/BaseTypes/Pixel.js
../../lib/OpenLayers/BaseTypes/Size.js
../../lib/OpenLayers/Console.js
../../lib/OpenLayers/Tween.js
../../lib/OpenLayers/Kinetic.js
../../lib/Rico/Color.js
../../lib/Rico/Corner.js
../../lib/OpenLayers/Events.js
../../lib/OpenLayers/Request.js
../../lib/OpenLayers/Request/XMLHttpRequest.js
../../lib/OpenLayers/Projection.js
../../lib/OpenLayers/Layer.js
../../lib/OpenLayers/Map.js
../../lib/OpenLayers/Icon.js
../../lib/OpenLayers/Marker.js
../../lib/OpenLayers/Popup.js
../../lib/OpenLayers/Marker/Box.js
../../lib/OpenLayers/Tile.js
../../lib/OpenLayers/Tile/Image.js
../../lib/OpenLayers/Layer/Image.js
../../lib/OpenLayers/Tile/Image/IFrame.js
../../lib/OpenLayers/Layer/EventPane.js
../../lib/OpenLayers/Layer/SphericalMercator.js
../../lib/OpenLayers/Layer/FixedZoomLevels.js
../../lib/OpenLayers/Layer/Google.js
../../lib/OpenLayers/Layer/Google/v3.js
../../lib/OpenLayers/Layer/Grid.js
../../lib/OpenLayers/Layer/HTTPRequest.js
../../lib/OpenLayers/Layer/MapGuide.js
../../lib/OpenLayers/Layer/MapServer.js
../../lib/OpenLayers/Layer/KaMapCache.js
../../lib/OpenLayers/Layer/KaMap.js
../../lib/OpenLayers/Layer/Markers.js
../../lib/OpenLayers/Layer/Text.js
../../lib/OpenLayers/Layer/WorldWind.js
../../lib/OpenLayers/Layer/ArcGIS93Rest.js
../../lib/OpenLayers/Layer/WMS.js
../../lib/OpenLayers/Layer/WMTS.js
../../lib/OpenLayers/Layer/ArcIMS.js
../../lib/OpenLayers/Layer/GeoRSS.js
../../lib/OpenLayers/Layer/Boxes.js
../../lib/OpenLayers/Layer/XYZ.js
../../lib/OpenLayers/Layer/OSMoffline.js
../../lib/OpenLayers/Layer/Bing.js
../../lib/OpenLayers/Layer/TMS.js
../../lib/OpenLayers/Layer/TileCache.js
../../lib/OpenLayers/Layer/Zoomify.js
../../lib/OpenLayers/Layer/ArcGISCache.js
../../lib/OpenLayers/Popup/Anchored.js
../../lib/OpenLayers/Popup/Framed.js
../../lib/OpenLayers/Popup/AnchoredBubble.js
../../lib/OpenLayers/Popup/FramedCloud.js
../../lib/OpenLayers/Feature.js
../../lib/OpenLayers/Feature/Vector.js
../../lib/OpenLayers/Handler.js
../../lib/OpenLayers/Handler/Click.js
../../lib/OpenLayers/Handler/Point.js
../../lib/OpenLayers/Handler/Hover.js
../../lib/OpenLayers/Handler/Path.js
../../lib/OpenLayers/Handler/Polygon.js
../../lib/OpenLayers/Handler/Feature.js
../../lib/OpenLayers/Handler/Drag.js
../../lib/OpenLayers/Handler/Pinch.js
../../lib/OpenLayers/Handler/RegularPolygon.js
../../lib/OpenLayers/Handler/Box.js
../../lib/OpenLayers/Handler/MouseWheel.js
../../lib/OpenLayers/Handler/Keyboard.js
../../lib/OpenLayers/Control.js
../../lib/OpenLayers/Control/Attribution.js
../../lib/OpenLayers/Control/Button.js
../../lib/OpenLayers/Control/ZoomBox.js
../../lib/OpenLayers/Control/ZoomToMaxExtent.js
../../lib/OpenLayers/Control/DragPan.js
../../lib/OpenLayers/Control/Navigation.js
../../lib/OpenLayers/Control/PinchZoom.js
../../lib/OpenLayers/Control/TouchNavigation.js
../../lib/OpenLayers/Control/MousePosition.js
../../lib/OpenLayers/Control/OverviewMap.js
../../lib/OpenLayers/Control/KeyboardDefaults.js
../../lib/OpenLayers/Control/PanZoom.js
../../lib/OpenLayers/Control/PanZoomBar.js
../../lib/OpenLayers/Control/Permalink.js
../../lib/OpenLayers/Control/ArgParser.js
../../lib/OpenLayers/Control/Scale.js
../../lib/OpenLayers/Control/ScaleLine.js
../../lib/OpenLayers/Control/Snapping.js
../../lib/OpenLayers/Control/LayerSwitcher.js
../../lib/OpenLayers/Control/Split.js
../../lib/OpenLayers/Control/DrawFeature.js
../../lib/OpenLayers/Control/DragFeature.js
../../lib/OpenLayers/Control/SelectFeature.js
../../lib/OpenLayers/Control/ModifyFeature.js
../../lib/OpenLayers/Control/Panel.js
../../lib/OpenLayers/Control/NavigationHistory.js
../../lib/OpenLayers/Control/Measure.js
../../lib/OpenLayers/Control/WMSGetFeatureInfo.js
../../lib/OpenLayers/Control/Graticule.js
../../lib/OpenLayers/Control/WMTSGetFeatureInfo.js
../../lib/OpenLayers/Control/TransformFeature.js
../../lib/OpenLayers/Control/SLDSelect.js
../../lib/OpenLayers/Geometry/Collection.js
../../lib/OpenLayers/Geometry.js
../../lib/OpenLayers/Geometry/Point.js
../../lib/OpenLayers/Geometry/MultiPoint.js
../../lib/OpenLayers/Geometry/Curve.js
../../lib/OpenLayers/Geometry/Polygon.js
../../lib/OpenLayers/Geometry/MultiLineString.js
../../lib/OpenLayers/Geometry/MultiPolygon.js
../../lib/OpenLayers/Renderer.js
../../lib/OpenLayers/Renderer/NG.js
../../lib/OpenLayers/Renderer/Elements.js
../../lib/OpenLayers/Renderer/SVG.js
../../lib/OpenLayers/Renderer/SVG2.js
../../lib/OpenLayers/Renderer/VML.js
../../lib/OpenLayers/Renderer/Canvas.js
../../lib/OpenLayers/Layer/Vector.js
../../lib/OpenLayers/Layer/PointGrid.js
../../lib/OpenLayers/Layer/Vector/RootContainer.js
../../lib/OpenLayers/Strategy.js
../../lib/OpenLayers/Strategy/Fixed.js
../../lib/OpenLayers/Strategy/Filter.js
../../lib/OpenLayers/Strategy/Cluster.js
../../lib/OpenLayers/Strategy/Paging.js
../../lib/OpenLayers/Strategy/Save.js
../../lib/OpenLayers/Strategy/BBOX.js
../../lib/OpenLayers/Strategy/Refresh.js
../../lib/OpenLayers/Filter.js
../../lib/OpenLayers/Filter/FeatureId.js
../../lib/OpenLayers/Filter/Logical.js
../../lib/OpenLayers/Filter/Spatial.js
../../lib/OpenLayers/Filter/Comparison.js
../../lib/OpenLayers/Filter/Function.js
../../lib/OpenLayers/Protocol.js
../../lib/OpenLayers/Protocol/HTTP.js
../../lib/OpenLayers/Protocol/WFS.js
../../lib/OpenLayers/Protocol/WFS/v1.js
../../lib/OpenLayers/Protocol/WFS/v1_0_0.js
../../lib/OpenLayers/Protocol/WFS/v1_1_0.js
../../lib/OpenLayers/Protocol/Script.js
../../lib/OpenLayers/Protocol/SOS/v1_0_0.js
../../lib/OpenLayers/Protocol/SOS.js
../../lib/OpenLayers/Layer/PointTrack.js
../../lib/OpenLayers/Style.js
../../lib/OpenLayers/StyleMap.js
../../lib/OpenLayers/Style2.js
../../lib/OpenLayers/Rule.js
../../lib/OpenLayers/Format.js
../../lib/OpenLayers/Format/QueryStringFilter.js
../../lib/OpenLayers/Format/XML/VersionedOGC.js
../../lib/OpenLayers/Format/XML.js
../../lib/OpenLayers/Format/Context.js
../../lib/OpenLayers/Format/ArcXML.js
../../lib/OpenLayers/Format/ArcXML/Features.js
../../lib/OpenLayers/Format/GML.js
../../lib/OpenLayers/Format/GML/v2.js
../../lib/OpenLayers/Format/GML/Base.js
../../lib/OpenLayers/Format/GML/v3.js
../../lib/OpenLayers/Format/KML.js
../../lib/OpenLayers/Format/Atom.js
../../lib/OpenLayers/Format/GeoRSS.js
../../lib/OpenLayers/Format/WFS.js
../../lib/OpenLayers/Format/WFSCapabilities.js
../../lib/OpenLayers/Format/WFSCapabilities/v1.js
../../lib/OpenLayers/Format/WFSCapabilities/v1_1_0.js
../../lib/OpenLayers/Format/WFSCapabilities/v1_0_0.js
../../lib/OpenLayers/Format/WFSDescribeFeatureType.js
../../lib/OpenLayers/Format/WMSDescribeLayer.js
../../lib/OpenLayers/Format/WMSDescribeLayer/v1_1.js
../../lib/OpenLayers/Format/WKT.js
../../lib/OpenLayers/Format/CQL.js
../../lib/OpenLayers/Format/OSM.js
../../lib/OpenLayers/Format/GPX.js
../../lib/OpenLayers/Format/Filter.js
../../lib/OpenLayers/Format/Filter/v1.js
../../lib/OpenLayers/Format/Filter/v1_0_0.js
../../lib/OpenLayers/Format/Filter/v1_1_0.js
../../lib/OpenLayers/Format/SLD.js
../../lib/OpenLayers/Format/SLD/v1.js
../../lib/OpenLayers/Format/SLD/v1_0_0.js
../../lib/OpenLayers/Format/OWSCommon.js
../../lib/OpenLayers/Format/OWSCommon/v1.js
../../lib/OpenLayers/Format/OWSCommon/v1_0_0.js
../../lib/OpenLayers/Format/OWSCommon/v1_1_0.js
../../lib/OpenLayers/Format/CSWGetDomain.js
../../lib/OpenLayers/Format/CSWGetDomain/v2_0_2.js
../../lib/OpenLayers/Format/CSWGetRecords.js
../../lib/OpenLayers/Format/CSWGetRecords/v2_0_2.js
../../lib/OpenLayers/Format/WFST.js
../../lib/OpenLayers/Format/WFST/v1.js
../../lib/OpenLayers/Format/WFST/v1_0_0.js
../../lib/OpenLayers/Format/WFST/v1_1_0.js
../../lib/OpenLayers/Format/Text.js
../../lib/OpenLayers/Format/JSON.js
../../lib/OpenLayers/Format/GeoJSON.js
../../lib/OpenLayers/Format/WMC.js
../../lib/OpenLayers/Format/WMC/v1.js
../../lib/OpenLayers/Format/WMC/v1_0_0.js
../../lib/OpenLayers/Format/WMC/v1_1_0.js
../../lib/OpenLayers/Format/WCSGetCoverage.js
../../lib/OpenLayers/Format/WMSCapabilities.js
../../lib/OpenLayers/Format/WMSCapabilities/v1.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_1.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_1_1.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_1_0.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_3.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_3_0.js
../../lib/OpenLayers/Format/WMSCapabilities/v1_1_1_WMSC.js
../../lib/OpenLayers/Format/SOSCapabilities.js
../../lib/OpenLayers/Format/SOSGetFeatureOfInterest.js
../../lib/OpenLayers/Format/WMSGetFeatureInfo.js
../../lib/OpenLayers/Format/SOSCapabilities/v1_0_0.js
../../lib/OpenLayers/Format/SOSGetObservation.js
../../lib/OpenLayers/Format/OWSContext.js
../../lib/OpenLayers/Format/OWSContext/v0_3_1.js
../../lib/OpenLayers/Format/WMTSCapabilities/v1_0_0.js
../../lib/OpenLayers/Format/WMTSCapabilities.js
../../lib/OpenLayers/Format/WPSCapabilities/v1_0_0.js
../../lib/OpenLayers/Format/WPSCapabilities.js
../../lib/OpenLayers/Format/WPSDescribeProcess.js
../../lib/OpenLayers/Format/WPSExecute.js
../../lib/OpenLayers/Format/XLS.js
../../lib/OpenLayers/Format/XLS/v1.js
../../lib/OpenLayers/Format/XLS/v1_1_0.js
../../lib/OpenLayers/Control/GetFeature.js
../../lib/OpenLayers/Format/OGCExceptionReport.js
../../lib/OpenLayers/Control/NavToolbar.js
../../lib/OpenLayers/Control/PanPanel.js
../../lib/OpenLayers/Control/ZoomOut.js
../../lib/OpenLayers/Control/Pan.js
../../lib/OpenLayers/Control/ZoomPanel.js
../../lib/OpenLayers/Control/ZoomIn.js
../../lib/OpenLayers/Control/EditingToolbar.js
../../lib/OpenLayers/Control/Geolocate.js
../../lib/OpenLayers/Symbolizer.js
../../lib/OpenLayers/Symbolizer/Point.js
../../lib/OpenLayers/Symbolizer/Text.js
../../lib/OpenLayers/Symbolizer/Raster.js
../../lib/OpenLayers/Lang/en.js
../../lib/OpenLayers/Lang.js
../..//lib/OpenLayers/Geometry/LineString.js
../..//lib/OpenLayers/Geometry/LinearRing.js
../..//lib/OpenLayers/Symbolizer/Line.js
../..//lib/OpenLayers/Symbolizer/Polygon.js

../img/mobile-zoombar.png

NETWORK:

64proxy.php

#jjj